# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dd103d53b82f8a98f803de441f03818d5fed643f057000bfb0e523f2a10c34cdc5c65035ea01c90089f5b3337223ba0c6ee0b523408837729d63b3ade19848e

test:
  secret_key_base: 98843abfddd5b5d70a0ca0a8532605a1ef4ed248648a14dd93eac9662984758f99caacc8db2e3e9f7309839fd8786b980e2d23494413a8ff845ee47623bd1c3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
